name: 'NPM Custom Action'
description: 'Installing and caching NOM packages'
inputs:
  folder-path:
    description: 'path to cache'
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: ${{ inputs.folder-path }}
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      run: npm install
      shell: bash