on:
    pull_request:
        types:
            - opened

jobs:
    testing-action:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Post PR comment
              uses: tbuccia14/docker-action-pr-giphy-comment@main
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                giphy-api-key: ${{ secrets.GIPHY_API_KEY }}

            - name: Post JS action PR comment
              uses: sidd-harth-7/js-action-pr-giphy-comment@1.0.0-alpha
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                giphy-api-key: ${{ secrets.GIPHY_API_KEY }}
